# Variables
@baseUrl = http://localhost:3333 

# Health Check
# @name healthCheck
GET {{baseUrl}}/health 

###

# Get Rooms 
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name":"Sala de teste",
    "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get Room Question
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Qustion
# @name createQuestion
POST {{baseUrl}}/rooms/91428972-52aa-459d-89ee-7e4a9bae6b2e/questions
Content-Type: application/json

{
    "question":"Qual a diferença de react e angular?"
}
