# -*- coding: utf-8 -*-
"""05.04.01 Exercícios if.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JjcqciIJtjIfCFgoiGJIHEAwsVXTME1Z

# Exercícios com if

## 1. Cálculo de Bônus

- Crie um programa que calcule e dê um print no bônus que os funcionários devem receber segundo a regra:

A meta é 1000 vendas.<br> 
Se o valor de vendas for maior ou igual a meta, o valor do bônus do funcionário é 10% do valor de vendas.<br>
Caso contrário o valor de bônus do funcionário é 0.<br>
Print o bônus dos 3 funcionários
"""

vendas_funcionario1 = 1000
vendas_funcionario2 = 770
vendas_funcionario3 = 2700

#crie seu código aqui

"""Resposta:
O funcionário 1 ganhou 100 de bônus
O funcionário 2 ganhou 0 de bônus
O funcionário 3 ganhou 270 de bônus

## 2. Cálculo de bônus com uma nova regra

- Agora, crie um novo código que calcule e dê um print no bônus dos funcionários novamente. Porém há uma nova regra nesse 2º caso:

A meta é 1000 vendas<br>
Agora, os funcionários que venderem muito acima da meta ganham mais bônus do que os outros. Então o bônus é definido da seguinte forma:<br>

- Se vendas funcionário for maior ou igual a 2000, então o bônus é de 15% sobre o valor de vendas
- Se vendas funcionário for menor do que 2000 e maior ou igual a 1000, então o bônus é de 10% sobre o valor de vendas
- Se vendas funcionário for menos do que 1000 então o bônus do funcionário é de 0.

Use as mesmas variáveis de vendas_funcionários
"""

#crie seu código aqui
#obs: há 2 formas de fazer, com if dentro de if ou então com if e elif. Escolha a que você preferir

"""Resposta:
O funcionário 1 ganhou 100 de bônus
O funcionário 2 ganhou 0 de bônus
O funcionário 3 ganhou 405 de bônus
"""

vendas_funcionario1 = 1000
vendas_funcionario2 = 770
vendas_funcionario3 = 2700
vendas = [vendas_funcionario1, vendas_funcionario2, vendas_funcionario3]

meta1 = 1000
meta2 = 2000
bonus1 = 0.1
bonus2 = 0.15

for i in range(len(vendas)):
    if vendas[i] >= meta2:
        print(f"Funcionario {i} ganhou um bonus de: {vendas[i]*bonus2}")
    elif vendas[i] >= meta1:
        print(f"Funcionario {i} ganhou um bonus de {vendas[i]*bonus1}")
    else:
        print(f"Funcionario {i} não ganhou bonus!")