nome = str(input('Seu nome completo: ')).strip()
div = nome.split()
sep = nome.split()
print('='*50)
print('Nome captalizado: {}'.format(nome.title()))
print('Nome em minusculo: {}'.format(nome.lower()))
print('Nome em maiusculo: {}'.format(nome.upper()))
print('Numero de letras do nome sem espaço: {}'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome é {}, e ele tem {} letras'.format(sep[0], len(sep[0])))
print('='*50)